- name: put values
  template: src=values.yml dest=/tmp/percona-xtradb-{{ percona_xtradb_helm_release }}.yml

- name: upgrade {{ percona_xtradb_helm_release }} release using a Helm chart
  shell: helm upgrade {{ percona_xtradb_helm_release }} stable/percona-xtradb-cluster --install --recreate-pods --namespace {{ k8s_namespace }} -f /tmp/percona-xtradb-{{ percona_xtradb_helm_release }}.yml
